services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:8080" # 将内部 8080 端口映射到主机的 8899 端口
    environment:
      - PASSWORD=${PASSWORD:-bupt2cs} # 可将 111111 修改为你想要的密码，默认为 your_password
    restart: unless-stopped
(base) suyb@gpu-delu3oksjn2e-1-test:~/proj/webplayer/docker$ env | grep -i proxy